### ISSUE TITLE
Support for dissector for ICMP Packets 

### ISSUE THREAD

**Issue by gabhijit** [ystero-dev/scalpel#29]

**Comment by hgupta12** [comment]
Sir, one of the teammates is working on ICMPv6. Does it come under this issue or should we create a separate one?

**Comment by gabhijit** [comment]
I guess it's a better idea to create a separate one for ICMPv6 as many of the types besides the standard Echo Request/Reply are different.

**Comment by hgupta12** [comment]
Sure sir, we'll make it.

**Comment by gabhijit** [comment]
Fixed by #38

**Comment by hgupta12** [comment]
Hi @gabhijit sir, should I open a new issue for adding dissection of the data part of ICMP packets or work on other issues?

**Comment by gabhijit** [comment]
@hgupta12 : It's a good idea to open a new issue.
